# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e08aee407d965c9d0b028b77504d94a1a97fae0c30bd8b973e7789e53ad8c3a6e163b90da801bb848a26339d7613fe5c52a7e6e2abffadd5ad3ecb79772dbe35

test:
  secret_key_base: f61e1728f9434eb92abef378fb1e40a4f1900e8db9020d42c3152e6b9c1841720de418d3679e5a7be05b4b31ffc436835cec18d904772f79cf20fc88cfddfe81

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
